### ISSUE TITLE
Error: Failed to parse Provisioning Profile content, error: plist: type mismatch: tried to decode array into value of type string

### ISSUE THREAD

**Issue by fpena** [bitrise-tools/codesigndoc#28]
There's an error while running 

`bash -l -c "$(curl -sfL https://raw.githubusercontent.com/bitrise-
tools/codesigndoc/master/_scripts/install_wrap-xcode.sh) --scheme=WeWine"`

[Here's](http://cloud.penya.cl/3W2A1z2a2U2I) the terminal output and the [instruction output](http://cloud.penya.cl/2u27000c3a0l).

**Comment by viktorbenei** [comment]
Thanks for reporting the issue! @fpena 

We'll try to find a solution for this issue ASAP, in the meantime: can you move out the `$HOME/Library/MobileDevice/Provisioning Profiles/A65CB364-2C49-4BC5-8A94-EF2A4E9846A4.mobileprovision` file to a temporary directory (e.g. to your Desktop), and run codesigndoc again?

_If possible, can you please also share this file with us through email/onsite chat, so that we can inspect what the issue can be with this file?_

**Comment by viktorbenei** [comment]
For reference, the related `codesigndoc` output (Xcode archive was successful):

```
INFO[21:06:01]  * Searching for Provisioning Profiles with App ID pattern: *.com.XXX.YYY 

------------------------------
First of all please make sure that you can Archive your app from Xcode.
codesigndoc only works if you can archive your app from Xcode.
If you can, and you get a valid IPA file if you export from Xcode,
please create an issue on GitHub at: https://github.com/bitrise-tools/codesigndoc/issues
with as many details & logs as you can share!
------------------------------

Error: Failed to export Provisioning Profiles, error: Error during Provisioning Profile search: Failed to read Provisioning Profile infos from file (path: /Users/REDACTED/Library/MobileDevice/Provisioning Profiles/A..-...-...-...-...A4.mobileprovision), error: Failed to parse Provisioning Profile content, error: plist: type mismatch: tried to decode array into value of type string
```

**Comment by fpena** [comment]
@viktorbenei I just shared with you over email the provisioning profile. Let me know how it goes.

**Comment by viktorbenei** [comment]
Thanks! Does `codesigndoc` work if you move this file out to your Desktop?

**Comment by fpena** [comment]
@viktorbenei what's the instruction I should specifically run?

**Comment by viktorbenei** [comment]
the same thing, just move out this file to your Desktop first

**Comment by fpena** [comment]
I get an error. 

<img width="964" alt="captura de pantalla 2016-11-30 a las 07 51 09" src="https://cloud.githubusercontent.com/assets/440097/20752920/d701d52c-b6d1-11e6-8ed1-0f47850054a2.png">

**Comment by viktorbenei** [comment]
you have a typo in the command - can you please copy paste the command from here: bash -l -c "$(curl -sfL https://raw.githubusercontent.com/bitrise-tools/codesigndoc/master/_scripts/install_wrap-xcode.sh)" or from bitrise.io ?

(There's a space in `/bitrise- tools/` in the URL, which should not be there)

**Comment by fpena** [comment]
@viktorbenei what should I do when asking for project or workspace file?

**Comment by viktorbenei** [comment]
What's printed there, just drag and drop the workspace (or project if you don't have a workspace) from Finder into Terminal

**Comment by fpena** [comment]
Sort of the same stuff. 

[Terminal](http://cloud.penya.cl/1h3Q3x3X2C0R) and [output](http://cloud.penya.cl/1c2q193M0K1P).

Also, image from terminal.

<img width="955" alt="captura de pantalla 2016-11-30 a las 08 15 12" src="https://cloud.githubusercontent.com/assets/440097/20753651/5861a748-b6d5-11e6-8aea-699764f566cb.png">

**Comment by viktorbenei** [comment]
Are you sure that you did move out the file from that directory? Can you please double check, that the file in the error does not exist in the "Provisioning Profiles" directory, and run `codesigndoc` after that?

**Comment by fpena** [comment]
It worked! It was my fault. I just copied the file into my desktop. 

Now I'm making a new build with the provisioning files and certificate from the output.

**Comment by viktorbenei** [comment]
In the meantime we'll check the prov profile, why that can't be parsed

**Comment by viktorbenei** [comment]
@fpena do you know how this Provisioning Profile was generated?

We checked it, and the issue is that the `com.apple.developer.team-identifier` property in the provisioning profile is an array instead of a string. It's an array with a single string item.

It seems strange, as we tested with many different provisioning profiles, and the value of `com.apple.developer.team-identifier` was always a string, not an array.

**Comment by viktorbenei** [comment]
v0.9.17 includes a fix so that it can now work with provisioning profiles like the one which caused the issue here.

Thanks for reporting the issue @fpena , and of course we'd still be interested to learn how a provisioning profile like this one can be created, we couldn't find a way to reproduce this issue with a new provisioning profile / to generate a provisioning profile like the one caused the issue.

**Comment by fpena** [comment]
@viktorbenei the provisioning I moved out the folder was very old (2014 aprox.). I generated inside the provisioning portal back then. 

Is that what you were asking?

**Comment by viktorbenei** [comment]
Yes, thank you @fpena - indeed that's what we suspect too, that the format was "normalized" a while back, and your profile was an "ancient" one - we didn't see a profile where `com.apple.developer.team-identifier` is an array instead of a string, and we have 3+ year old profiles too.

**Comment by fpena** [comment]
ok, good we had that clarified. Thanks.

**Comment by User2004** [comment]
https://webappcodes.com/entitlements-mismatch-error-in-xcode

Mismatch profile issue

**Comment by bitce** [comment]
@User2004 what is it that you're experiencing exactly? Could you include the terminal output?

**Comment by fehersanyi-bitrise** [comment]
Hello @User2004, Could you please copy the build's url here please?
