### ISSUE TITLE
Using specific build configuration

### ISSUE THREAD

**Issue by koxon** [bitrise-tools/codesigndoc#74]
Hello,

I have 6 build configurations. If I don't specify the configuration to use to xcodebuild, I get issues. 
I think codesigndoc uses the default Release configuration build which I don't have anymore.

What's the way to provide a specific configuration build so I can archive correctly?

I should be able to provide this option for example:
-configuration "Release (Dev)"  

thank you

**Comment by viktorbenei** [comment]
Hi @koxon ,

I'll bring this up for a discussion with the team.

As a workaround for now:

> What's the way to provide a specific configuration build so I can archive correctly?

Simply open the project in Xcode and set the Archive action of the Scheme to the configuration you want to:

![screen_shot_2018-04-20_at_13_06_27](https://user-images.githubusercontent.com/430618/39047853-b946888a-449b-11e8-8ee4-adbd3e17698e.png)

![screen_shot_2018-04-20_at_13_06_40](https://user-images.githubusercontent.com/430618/39047867-c2fed738-449b-11e8-90fc-f0adaf069214.png)

You can of course duplicate the Scheme and set the config there if you prefer that instead of modifying the current one.

If you'd have any questions just let us know! :)

**Comment by koxon** [comment]
thanks

**Comment by viktorbenei** [comment]
No problem at all @koxon :wink:
